import { describe, it, expect } from 'vitest'
import { mkdtempSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { parse } from 'yaml'
import { scaffoldFromIntrospection } from '../src/semantic/scaffold.ts'
import { configToYaml, ensureWorkbenchInclude, workbenchPathFor } from '../src/semantic/serialize.ts'
import { buildSemanticSummary } from '../src/semantic/summary.ts'
import { SemanticLayer } from '../src/semantic/layer.ts'
import type { SchemaInfo } from '../src/types.ts'

const tmp = (): string => mkdtempSync(join(tmpdir(), 'rd-sem-'))

describe('scaffoldFromIntrospection', () => {
  const schema: SchemaInfo = {
    datasource: 'demo',
    dialect: 'sqlite',
    truncated: false,
    tables: [
      {
        name: 'orders',
        type: 'table',
        columns: [
          { name: 'id', dataType: 'INTEGER' },
          { name: 'amount', dataType: 'DECIMAL' },
          { name: 'user_id', dataType: 'INTEGER' },
          { name: 'status', dataType: 'VARCHAR' },
          { name: 'created_at', dataType: 'DATETIME' },
        ],
      },
      { name: 'v_recent', type: 'view', columns: [{ name: 'x', dataType: 'INTEGER' }] },
    ],
  }

  it('creates one count metric per table and skips views', () => {
    const result = scaffoldFromIntrospection(schema, 'demo')
    expect(result.entities).toHaveLength(1)
    expect(result.entities[0].table).toBe('orders')
    expect(result.metrics.some((m) => m.name === 'orders_count' && m.agg === 'count')).toBe(true)
    expect(result.metrics.some((m) => m.name === 'v_recent_count')).toBe(false)
  })

  it('derives sum/avg metrics for numeric columns and a time field', () => {
    const result = scaffoldFromIntrospection(schema, 'demo')
    expect(result.metrics.some((m) => m.name === 'orders_amount_sum' && m.agg === 'sum')).toBe(true)
    expect(result.metrics.some((m) => m.name === 'orders_amount_avg' && m.agg === 'avg')).toBe(true)
    // user_id is numeric but looks like a surrogate key → skipped
    expect(result.metrics.some((m) => m.name === 'orders_user_id_sum')).toBe(false)
    expect(result.entities[0].timeField).toBe('created_at')
  })
})

describe('serialize', () => {
  it('configToYaml round-trips entities and metrics', () => {
    const yaml = configToYaml({
      entities: [{ table: 'orders', label: '订单' }],
      metrics: [{ name: 'gmv', entity: 'orders', agg: 'sum', measure: 'amount' }],
    })
    const parsed = parse(yaml) as Record<string, unknown>
    expect(parsed.entities).toHaveLength(1)
    expect(parsed.metrics).toHaveLength(1)
    expect(yaml.startsWith('# Generated by the Database Workbench')).toBe(true)
  })

  it('omits empty sections', () => {
    const yaml = configToYaml({ entities: [], metrics: [], terms: [] })
    expect(yaml).not.toContain('entities:')
  })

  it('ensureWorkbenchInclude appends once and is idempotent', () => {
    const dir = tmp()
    const root = join(dir, 'semantic.yaml')
    writeFileSync(root, 'include:\n  - ./a.yaml\n  - ./b.yaml\n')
    expect(ensureWorkbenchInclude(root, './semantic.workbench.yaml')).toBe(true)
    const after = parse(readFileSync(root, 'utf8')) as { include: string[] }
    expect(after.include).toEqual(['./a.yaml', './b.yaml', './semantic.workbench.yaml'])
    // second call is a no-op
    expect(ensureWorkbenchInclude(root, './semantic.workbench.yaml')).toBe(false)
  })

  it('workbenchPathFor derives a sidecar name', () => {
    expect(workbenchPathFor('/x/semantic.yaml', '/cwd')).toBe('/x/semantic.workbench.yaml')
    expect(workbenchPathFor('', '/cwd')).toBe(join('/cwd', 'semantic.workbench.yaml'))
  })
})

describe('buildSemanticSummary', () => {
  it('reports ok with counts and locale-rendered issues', () => {
    const dir = tmp()
    const file = join(dir, 'semantic.yaml')
    writeFileSync(file, [
      'defaults:',
      '  datasource: demo',
      'entities:',
      '  - table: orders',
      '    label: 订单',
      'metrics:',
      '  - name: gmv',
      '    entity: orders',
      '    agg: sum',
      '    measure: amount',
    ].join('\n'))
    const layer = new SemanticLayer(file)
    const summary = buildSemanticSummary(layer, 'zh')
    expect(summary.state).toBe('ok')
    expect(summary.counts).toEqual({ entities: 1, metrics: 1, terms: 0 })
    expect(summary.metrics[0].name).toBe('gmv')
  })

  it('reports parse-error when the file is broken', () => {
    const dir = tmp()
    const file = join(dir, 'broken.yaml')
    writeFileSync(file, 'metrics:\n  - name: gmv\n    : : :\n  bad indentation')
    const layer = new SemanticLayer(file)
    const summary = buildSemanticSummary(layer, 'zh')
    expect(summary.state).toBe('parse-error')
    expect(summary.error).toBeDefined()
  })

  it('reports empty when no file is configured', () => {
    const layer = new SemanticLayer(undefined)
    const summary = buildSemanticSummary(layer, 'zh')
    expect(summary.state).toBe('empty')
  })
})
