/**
 * Semantic layer (de)serialization helpers for workbench authoring.
 *
 * The workbench editor owns a single **dedicated** file
 * (`<rootDir>/semantic.workbench.yaml`) so it never overwrites the operator's
 * hand-authored multi-file setup. These helpers write that file and, when a
 * root file exists, non-destructively add it to the root's `include` list.
 *
 * @module dsh-rd-data-analysis/semantic/serialize
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { dirname, isAbsolute, relative, resolve } from 'node:path'
import { parse, stringify } from 'yaml'
import type { SemanticConfig } from './types.ts'

/** Build canonical YAML for a user-authored semantic fragment. */
export function configToYaml(config: SemanticConfig): string {
  const doc: Record<string, unknown> = {}
  if (config.entities !== undefined && config.entities.length > 0) doc.entities = config.entities
  if (config.metrics !== undefined && config.metrics.length > 0) doc.metrics = config.metrics
  if (config.terms !== undefined && config.terms.length > 0) doc.terms = config.terms
  const header = '# Generated by the Database Workbench semantic editor.\n# Safe to edit by hand; re-saving the editor overwrites this file.\n'
  return header + stringify(doc)
}

/** Write semantic YAML to disk (overwrites). */
export function writeSemanticFile(path: string, content: string): void {
  writeFileSync(path, content, 'utf8')
}

/**
 * Ensure `rootPath` includes `workbenchPath` so the layer loads it.
 *
 * Non-destructive: it only appends to the `include` list when the entry is
 * absent, preserving every other key and the file's comments around them is
 * best-effort (yaml round-trips, so surrounding comments outside the include
 * key may be lost — the include key itself is preserved).
 *
 * @returns true when the file was modified.
 */
export function ensureWorkbenchInclude(rootPath: string, workbenchPath: string): boolean {
  if (!existsSync(rootPath)) return false
  let root: unknown
  try {
    root = parse(readFileSync(rootPath, 'utf8'))
  } catch {
    return false
  }
  if (root === null || typeof root !== 'object') return false
  const obj = root as Record<string, unknown>
  const rel = isAbsolute(workbenchPath)
    ? `./${relative(dirname(rootPath), workbenchPath).split('\\').join('/')}`
    : workbenchPath
  const includes = obj.include
  const list = Array.isArray(includes) ? (includes as unknown[]).map(String) : []
  if (list.includes(rel)) return false
  obj.include = [...list, rel]
  writeFileSync(rootPath, stringify(obj), 'utf8')
  return true
}

/**
 * Compute the workbench file path for a given root semantic file.
 *
 * @param rootFile the configured `semanticFile` (may be empty => no root yet).
 * @param baseDir fallback directory when there is no root (e.g. process cwd).
 */
export function workbenchPathFor(rootFile: string | undefined, baseDir: string): string {
  if (rootFile === undefined || rootFile === '') {
    return resolve(baseDir, 'semantic.workbench.yaml')
  }
  const dir = dirname(rootFile)
  const base = rootFile.replace(/(\.ya?ml)$/i, '')
  return `${base}.workbench.yaml` // semantic.yaml -> semantic.workbench.yaml
}
